MAX_LEN: 50
SEED: 2809
DATA_TRAIN: './data/train.csv'
PHOBERT_VERSION: 'vinai/phobert-base'
EPOCHS: 20
BATCH_SIZE: 8
PATH_MODEL: './models/phobert/phobert.bin'
PATH_METRIC: './models/phobert/metrics.pt'
LOAD_CHECKPOINT: 0